apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: {{appName}}
  namespace: personbruker
  labels:
    team: personbruker
spec:
  image: {{image}}
  port: 8081
  liveness:
    path: /internal/isAlive
    initialDelay: 5
    timeout: 10
  readiness:
    path: /internal/isReady
    initialDelay: 5
    timeout: 10
  ingresses:
    - {{ingress}}
  envFrom:
    - secret: cms-migrator
    - secret: {{instanceSecret}}
  env:
  {{#each env as |var|}}
    - name: {{var.name}}
      value: {{var.value}}
  {{/each}}
  openSearch:
    access: readwrite
    instance: opensearch-personbruker-enonic-cms-archive
  replicas:
    min: 1
    max: 1
  accessPolicy:
    outbound:
      external:
        - host: {{cmsHost}}
  resources:
    requests:
      cpu: 250m
      memory: 500Mi
    limits:
      memory: 2000Mi