apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: {{appName}}
  namespace: personbruker
  labels:
    team: personbruker
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "100m"
spec:
  image: {{image}}
  port: 8081
  liveness:
    path: /internal/isAlive
    initialDelay: 5
    timeout: 30
  readiness:
    path: /internal/isReady
    initialDelay: 5
    timeout: 30
  ingresses:
    - {{ingress}}
  envFrom:
    - secret: {{secret}}
  env:
  {{#each env as |var|}}
    - name: {{var.name}}
      value: {{var.value}}
  {{/each}}
  openSearch:
    access: admin
    instance: enonic-cms-archive
  replicas:
    min: 1
    max: 1
    disableAutoScaling: true
  accessPolicy:
    outbound:
      external:
        - host: {{cmsHost}}
  resources:
    requests:
      cpu: 3000m
      memory: 4000Mi
    limits:
      memory: 8000Mi