apiVersion: aiven.io/v1alpha1
kind: OpenSearch
metadata:
  labels:
    team: personbruker
  name: opensearch-personbruker-enonic-cms-archive
  namespace: personbruker
spec:
  plan: startup-4
  project: nav-prod
