name: Build and deploy application
on:
  workflow_dispatch:
    inputs:
      cmsEnv:
        description: 'CMS env'
        required: true
        default: sbs
        type: choice
        options:
          - sbs

jobs:
  build:
    name: Build and deploy
    runs-on: ubuntu-latest
    permissions:
      contents: "read"
      id-token: "write"
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Setup java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17
      - uses: actions/cache@v3
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Build application
        run: |
          ./gradlew clean build
      - name: Build and push docker image
        uses: nais/docker-build-push@v0
        id: docker-push
        with:
          team: personbruker
          project_id: ${{ vars.NAIS_MANAGEMENT_PROJECT_ID }}
          identity_provider: ${{ secrets.NAIS_WORKLOAD_IDENTITY_PROVIDER }}
      - name: Deploy to nais
        uses: nais/deploy/actions/deploy@v2
        env:
          CLUSTER: prod-gcp
          RESOURCE: ./nais/app.yml
          VAR: image=${{steps.docker-push.outputs.image}}
          VARS: ./nais/vars/vars-${{ inputs.cmsEnv }}.json
